DRIVER_VERSION="${DRIVER_VERSION}"
DRIVER_KIND="${DRIVER_KIND}"
NVIDIA_CONTAINER_TOOLKIT_VER="1.19.1"
NVIDIA_PACKAGES="libnvidia-container1 libnvidia-container-tools nvidia-container-toolkit-base nvidia-container-toolkit"
AMD_PACKAGES="amdgpu-core amdgpu-dkms amdgpu-dkms-firmware rocm-core rocm-smi-lib rocminfo"
AMD_REQUIRED_PACKAGES="amdgpu-core amdgpu-dkms amdgpu-dkms-firmware rocm-core rocm-smi-lib rocminfo hsa-rocr libdrm2-amdgpu libdrm-amdgpu-amdgpu1 libdrm-amdgpu-common"
GPU_DEST="/usr/bin"
