DRIVER_VERSION="${DRIVER_VERSION}"
DRIVER_KIND="${DRIVER_KIND}"
NVIDIA_CONTAINER_TOOLKIT_VER="1.17.2"
NVIDIA_PACKAGES="libnvidia-container1 libnvidia-container-tools nvidia-container-toolkit-base nvidia-container-toolkit"
GPU_DEST="/usr/local/nvidia"
