DRIVER_VERSION="${DRIVER_VERSION}"
NVIDIA_DOCKER_VERSION="2.8.0-1"
NVIDIA_CONTAINER_RUNTIME_VERSION="3.6.0"
NVIDIA_CONTAINER_TOOLKIT_VER="1.6.0"
NVIDIA_PACKAGES="libnvidia-container1 libnvidia-container-tools nvidia-container-toolkit"
GPU_DEST="/usr/local/nvidia"
