apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "computedomain.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "computedomain.labels" . | nindent 4 }}
    {{- if .Values.aks.managedByLabels.enabled }}
    kubernetes.azure.com/managedby: aks
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
