apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "computedomain.name" . }}
  namespace: {{ include "computedomain.namespace" . }}
  labels:
    {{- include "computedomain.labels" . | nindent 4 }}
