name: Building and Pushing to MCR
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          bump_each_commit: false
          version_format: "v${major}.${minor}.${patch}-${increment}-sha-${GITHUB_SHA:0:6}"
        id: semver
      - name: 'Check version'
        run: |
          echo "version is ${{ steps.semver.outputs.version }}"
          echo "version is ${{ steps.semver.outputs.version_tag }}"
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
          set -x
          echo "tag is: "
          echo ${{ steps.semver.outputs.version }}
          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new --output=type=docker -t ${{ secrets.AZURE_REGISTRY_SERVER }}/public/aks/aks-gpu:${{ steps.semver.outputs.version }} .
          az acr login -n ${{ secrets.AZURE_REGISTRY_SERVER }}
          docker images
          # docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/public/aks/aks-gpu:${{ steps.semver.outputs.version }}
          # echo "acr push done"
      - name: Move cache
        run: |
          rm -r /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache