name: Building and Pushing to MCR
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read

jobs: 
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          bump_each_commit: true
          format: "${major}.${minor}.${patch}-${increment}"
        id: semver
      - name: 'Check version'
        run: |
          echo "version is ${{ steps.semver.outputs.version }}"
          echo "version is ${{ steps.semver.outputs.version_tag }}"
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run Azure CLI commands'
        run: |
          docker build -f Dockerfile -t ${{ secrets.AZURE_REGISTRY_SERVER }}/public/aks/aks-gpu:v${{ steps.semver.outputs.version }} .
          az acr login -n ${{ secrets.AZURE_REGISTRY_SERVER }}
          # docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/public/aks/aks-gpu:v${{ steps.semver.outputs.version }}
          # echo "acr push done"