on:
  # workflow_call: {}
  push:
    branches:
      - cameissner/oidc
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
jobs:
  get-app-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_KV_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_KV_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_KV_SUBSCRIPTION_ID }}

      - name: Get app credentials
        id: app-credentials
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            CLIENT_ID=$(az keyvault secret show --vault-name ${{ secrets.VAULT_NAME }} -n ${{ secrets.APP_CLIENT_ID_SECRET_NAME }} | jq -r '.value')
            echo "::add-mask::$CLIENT_ID"
            echo "APP_CLIENT_ID=$CLIENT_ID" >> $GITHUB_OUTPUT
            
            # https://github.com/actions/create-github-app-token?tab=readme-ov-file#inputs
            PRIVATE_KEY=$(az keyvault secret show --vault-name ${{ secrets.VAULT_NAME }} -n dummy-private-key | jq -r '.value' | awk 'BEGIN {ORS="\\n"} {print}' | head -c -2) &> /dev/null
            echo "DUMMY PRIVATE KEY: $PRIVATE_KEY"
            echo "::add-mask::$PRIVATE_KEY"
            echo "$PRIVATE_KEY" >> $GITHUB_OUTPUT