on:
  # workflow_call: {}
  push:
    branches:
      - cameissner/oidc
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
jobs:
  get-app-credentials:
    name: Get Assistant GitHub App Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_KV_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_KV_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_KV_SUBSCRIPTION_ID }}

      - name: Get assistant private key
        id: get-private-key
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            # https://github.com/actions/create-github-app-token?tab=readme-ov-file#inputs
            private_key=$(az keyvault secret show --vault-name ${{ secrets.VAULT_NAME }} -n dummy-private-key --query value -o tsv | sed 's/$/\\n/g' | tr -d '\n' | head -c -2) &> /dev/null
            echo "::add-mask::$private_key"
            echo "private-key=$private_key" >> $GITHUB_OUTPUT

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ steps.get-private-key.outputs.private-key }}